version: '3'

services:
  flask1:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "5001:5000"

  flask2:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "5002:5000"

  flask3:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "5003:5000"

  loadbalancer:
    build:
      context: .
      dockerfile: Dockerfile_loadbalancer
    ports:
      - "8080:8080"
